//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.STOCKs = new HashSet<STOCK>();
            this.CASHIERs = new HashSet<CASHIER>();
            this.STOCKs1 = new HashSet<STOCK>();
            this.FARMERS_MARKET = new HashSet<FARMERS_MARKET>();
        }
    
        public int CustomerId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> AccountBalance { get; set; }
    
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<CASHIER> CASHIERs { get; set; }
        public virtual ICollection<STOCK> STOCKs1 { get; set; }
        public virtual ICollection<FARMERS_MARKET> FARMERS_MARKET { get; set; }
    }
}
