//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARMERS_MARKET
    {
        public FARMERS_MARKET()
        {
            this.CASHIERs = new HashSet<CASHIER>();
            this.CUSTODIANs = new HashSet<CUSTODIAN>();
            this.SALES_ASSOCIATE = new HashSet<SALES_ASSOCIATE>();
            this.STOCKs = new HashSet<STOCK>();
            this.FARMERs = new HashSet<FARMER>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public string FMName { get; set; }
        public string Address { get; set; }
        public string Hours { get; set; }
        public int NumberOfSuppliers { get; set; }
        public int ProprietorId { get; set; }
    
        public virtual ICollection<CASHIER> CASHIERs { get; set; }
        public virtual ICollection<CUSTODIAN> CUSTODIANs { get; set; }
        public virtual PROPIETOR PROPIETOR { get; set; }
        public virtual ICollection<SALES_ASSOCIATE> SALES_ASSOCIATE { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<FARMER> FARMERs { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
