//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD
    {
        public GOOD()
        {
            this.FARMERs = new HashSet<FARMER>();
        }
    
        public int GoodId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<FARMER> FARMERs { get; set; }
    }
}
