//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db254614719227434d8463a494003807b5Entities : DbContext
    {
        public db254614719227434d8463a494003807b5Entities()
            : base("name=db254614719227434d8463a494003807b5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CASHIER> CASHIERs { get; set; }
        public DbSet<CUSTODIAN> CUSTODIANs { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<FARMER> FARMERs { get; set; }
        public DbSet<FARMERS_MARKET> FARMERS_MARKET { get; set; }
        public DbSet<GOOD> GOODs { get; set; }
        public DbSet<PROPIETOR> PROPIETORs { get; set; }
        public DbSet<SALES_ASSOCIATE> SALES_ASSOCIATE { get; set; }
        public DbSet<STOCK> STOCKs { get; set; }
    }
}
