//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIETOR
    {
        public PROPIETOR()
        {
            this.CASHIERs = new HashSet<CASHIER>();
            this.CUSTODIANs = new HashSet<CUSTODIAN>();
            this.FARMERS_MARKET = new HashSet<FARMERS_MARKET>();
            this.SALES_ASSOCIATE = new HashSet<SALES_ASSOCIATE>();
        }
    
        public string FName { get; set; }
        public string LName { get; set; }
        public int ProprietorId { get; set; }
    
        public virtual ICollection<CASHIER> CASHIERs { get; set; }
        public virtual ICollection<CUSTODIAN> CUSTODIANs { get; set; }
        public virtual ICollection<FARMERS_MARKET> FARMERS_MARKET { get; set; }
        public virtual ICollection<SALES_ASSOCIATE> SALES_ASSOCIATE { get; set; }
    }
}
