//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ASSOCIATE
    {
        public int SalesId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<double> HourlyPay { get; set; }
        public Nullable<int> NumberOfYearsEmployed { get; set; }
        public string FMName { get; set; }
        public int ProprietorId { get; set; }
    
        public virtual FARMERS_MARKET FARMERS_MARKET { get; set; }
        public virtual PROPIETOR PROPIETOR { get; set; }
    }
}
