//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public STOCK()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.CUSTOMERs1 = new HashSet<CUSTOMER>();
            this.FARMERS_MARKET = new HashSet<FARMERS_MARKET>();
        }
    
        public int StockId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs1 { get; set; }
        public virtual ICollection<FARMERS_MARKET> FARMERS_MARKET { get; set; }
    }
}
